# Generated by Django 3.1.4 on 2020-12-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201213_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='acrors',
            new_name='actors',
        ),
    ]
